package delco.twitter.scraping.model.enumerations;

public enum SyntaxEnum {

    ADJECTIVE, ADJECTIVE_COMPARATIVE, ADJECTIVE_SUPERLATIVE,
    WHADVERB, NOUN_SINGULAR, NOUN_PLURAL, PROPER_NOUN_SINGULAR,
    PROPER_NOUN_PLURAL, ADVERB, ADVERB_COMPARATIVE, ADVERB_SUPERLATIVE, NONE,
    EMOJI, GROTESQUE, KITSCH
}
